version: "3.8"

x-logging-config: &logging
  logging:
    driver: json-file
    options:
      tag: "{{.ImageName}}|{{.Name}}"
  networks:
    - loki

x-resources-limits: &resources
  cpu: 0.5
  mem_limit: "512M"

services:
  python_app:
    image: alkaitagi/inno-f21-doe:latest
    ports:
      - 5000:5000
    <<: *logging
    <<: *resources
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    <<: *logging
    <<: *resources
  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - 3000:3000
    <<: *logging
    <<: *resources
  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - 9080:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    <<: *logging
    <<: *resources
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    <<: *logging
    <<: *resources
networks:
  loki:
