apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: alkaitagi/inno-f21-doe:latest
        ports:
        - containerPort: 5000
