# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: alkaitagi/inno-f21-doe
  pullPolicy: IfNotPresent
  tag: latest
  port: 5000
  workDir: home/app/files

secrets:
  name: python-secret
  username: python-app # Change to your secret username

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    cpu: ".2"
    memory: "100Mi"
  limits:
    cpu: ".5"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
